import json

rows = [
    { "lxx": 1, "masoretic": 1, "title_ar": "طوبى للرجل", "note": "" },
    { "lxx": 2, "masoretic": 2, "title_ar": "لماذا ارتبكت الأمم", "note": "" },
    { "lxx": 3, "masoretic": 3, "title_ar": "يا رب لماذا كثر الذين يحزنونني", "note": "" },
    { "lxx": 4, "masoretic": 4, "title_ar": "لدى دعائي أجبني يا إله بري", "note": "" },
    { "lxx": 5, "masoretic": 5, "title_ar": "أصغ يا رب إلى كلامي", "note": "" },
    { "lxx": 6, "masoretic": 6, "title_ar": "يا رب لا تؤدبني بغضبك", "note": "" },
    { "lxx": 7, "masoretic": 7, "title_ar": "يا رب إلهي عليك توكلت", "note": "" },
    { "lxx": 8, "masoretic": 8, "title_ar": "يا رب سيدنا ما أعظ اسمك", "note": "" },
    { "lxx": 9, "masoretic": 9, "title_ar": "أحمدك يا رب من كل قلبي", "note": "LXX 9-10 = MT 9 (acrostic)" },
    { "lxx": 10, "masoretic": 9, "title_ar": "لماذا يا رب تقف بعيداً", "note": "LXX 9-10 = MT 9 (acrostic continued)" },
    { "lxx": 11, "masoretic": 11, "title_ar": "على الرب توكلت", "note": "" },
    { "lxx": 12, "masoretic": 12, "title_ar": "خلاص يا رب", "note": "" },
    { "lxx": 13, "masoretic": 13, "title_ar": "إلى متى يا رب تنساني", "note": "" },
    { "lxx": 14, "masoretic": 14, "title_ar": "قال الجاهل في قلبه", "note": "" },
    { "lxx": 15, "masoretic": 15, "title_ar": "يا رب من يسكن في مسكنك", "note": "" },
    { "lxx": 16, "masoretic": 16, "title_ar": "احفظني يا رب", "note": "" },
    { "lxx": 17, "masoretic": 17, "title_ar": "اسمع يا رب بري", "note": "" },
    { "lxx": 18, "masoretic": 18, "title_ar": "أحبك يا رب قوتي", "note": "" },
    { "lxx": 19, "masoretic": 19, "title_ar": "السماء تحدث بمجد الله", "note": "" },
    { "lxx": 20, "masoretic": 20, "title_ar": "يستجيب لك الرب يوم الضيق", "note": "" },
    { "lxx": 21, "masoretic": 21, "title_ar": "يا رب بقوتك يفرح الملك", "note": "" },
    { "lxx": 22, "masoretic": 22, "title_ar": "إلهي إلهي لماذا تركتني", "note": "" },
    { "lxx": 23, "masoretic": 23, "title_ar": "الرب راعي فلا يعوزني شيء", "note": "" },
    { "lxx": 24, "masoretic": 24, "title_ar": "للرب الأرض وملؤها", "note": "" },
    { "lxx": 25, "masoretic": 25, "title_ar": "إليك يا رب رفعت نفسي", "note": "" },
    { "lxx": 26, "masoretic": 26, "title_ar": "احكم لي يا رب", "note": "" },
    { "lxx": 27, "masoretic": 27, "title_ar": "الرب نوري وخلاصي", "note": "" },
    { "lxx": 28, "masoretic": 28, "title_ar": "إليك يا رب أصرخ", "note": "" },
    { "lxx": 29, "masoretic": 29, "title_ar": "قدموا للرب يا أبناء الله", "note": "" },
    { "lxx": 30, "masoretic": 30, "title_ar": "أعظمك يا رب", "note": "" },
    { "lxx": 31, "masoretic": 31, "title_ar": "عليك يا رب توكلت", "note": "" },
    { "lxx": 32, "masoretic": 32, "title_ar": "طوبى للذين غفرت آثامهم", "note": "" },
    { "lxx": 33, "masoretic": 33, "title_ar": "ترنموا أيها الصديقون", "note": "" },
    { "lxx": 34, "masoretic": 34, "title_ar": "أبارك الرب في كل حين", "note": "" },
    { "lxx": 35, "masoretic": 35, "title_ar": "خاصم يا رب مخاصمي", "note": "" },
    { "lxx": 36, "masoretic": 36, "title_ar": "يقول الأثيم في قلبه", "note": "" },
    { "lxx": 37, "masoretic": 37, "title_ar": "لا تغر لكثرة الأشرار", "note": "" },
    { "lxx": 38, "masoretic": 38, "title_ar": "يا رب لا تؤدبني بغضبك", "note": "" },
    { "lxx": 39, "masoretic": 39, "title_ar": "قلت أحفظ طريقي", "note": "" },
    { "lxx": 40, "masoretic": 40, "title_ar": "انتظاراً انتظرت الرب", "note": "" },
    { "lxx": 41, "masoretic": 41, "title_ar": "طوبى لمن يفهم المسكين", "note": "" },
    { "lxx": 42, "masoretic": 42, "title_ar": "كما يشتاق الأيل إلى جداول المياه", "note": "" },
    { "lxx": 43, "masoretic": 43, "title_ar": "احكم لي يا رب", "note": "" },
    { "lxx": 44, "masoretic": 44, "title_ar": "يا رب بآذاننا سمعنا", "note": "" },
    { "lxx": 45, "masoretic": 45, "title_ar": "فاض قلبي بالكلام الصالح", "note": "" },
    { "lxx": 46, "masoretic": 46, "title_ar": "الله لنا ملجأ وقوة", "note": "" },
    { "lxx": 47, "masoretic": 47, "title_ar": "صفقوا بأيديكم يا شعوب", "note": "" },
    { "lxx": 48, "masoretic": 48, "title_ar": "عظيم هو الرب", "note": "" },
    { "lxx": 49, "masoretic": 49, "title_ar": "اسمعوا هذا يا جميع الشعوب", "note": "" },
    { "lxx": 50, "masoretic": 50, "title_ar": "إله الآلهة الرب تكلم", "note": "" },
    { "lxx": 51, "masoretic": 51, "title_ar": "ارحمني يا الله", "note": "المزمور 50 في الأجبية (LXX 50) = مز 51 عبري - المزمور التوبة" },
    { "lxx": 52, "masoretic": 52, "title_ar": "لماذا تفتخر بالشر", "note": "" },
    { "lxx": 53, "masoretic": 53, "title_ar": "قال الجاهل في قلبه", "note": "" },
    { "lxx": 54, "masoretic": 54, "title_ar": "يا رب باسمك خلصني", "note": "" },
    { "lxx": 55, "masoretic": 55, "title_ar": "أصغ يا رب إلى صلاتي", "note": "" },
    { "lxx": 56, "masoretic": 56, "title_ar": "ارحمني يا الله", "note": "" },
    { "lxx": 57, "masoretic": 57, "title_ar": "ارحمني يا الله ارحمني", "note": "" },
    { "lxx": 58, "masoretic": 58, "title_ar": "هل بالحق تتكلمون العدل", "note": "" },
    { "lxx": 59, "masoretic": 59, "title_ar": "نجني من أعدائي يا إلهي", "note": "" },
    { "lxx": 60, "masoretic": 60, "title_ar": "يا رب رذلتنا وبددتنا", "note": "" },
    { "lxx": 61, "masoretic": 61, "title_ar": "اسمع يا رب صرختي", "note": "" },
    { "lxx": 62, "masoretic": 62, "title_ar": "إلهي إليك أسكت", "note": "" },
    { "lxx": 63, "masoretic": 63, "title_ar": "يا إلهي إليك أبتكر", "note": "" },
    { "lxx": 64, "masoretic": 64, "title_ar": "اسمع يا إلهي صوتي", "note": "" },
    { "lxx": 65, "masoretic": 65, "title_ar": "لك التسبيح يا الله في صهيون", "note": "" },
    { "lxx": 66, "masoretic": 66, "title_ar": "اهتفوا لله يا كل الأرض", "note": "" },
    { "lxx": 67, "masoretic": 67, "title_ar": "يرأف الله علينا ويباركنا", "note": "" },
    { "lxx": 68, "masoretic": 68, "title_ar": "يقوم الله ويتبدد أعداؤه", "note": "" },
    { "lxx": 69, "masoretic": 69, "title_ar": "خلصني يا الله", "note": "" },
    { "lxx": 70, "masoretic": 70, "title_ar": "يا الله إلى نجادتي", "note": "" },
    { "lxx": 71, "masoretic": 71, "title_ar": "عليك يا رب توكلت", "note": "" },
    { "lxx": 72, "masoretic": 72, "title_ar": "يا الله أعطِ أحكامك للملك", "note": "" },
    { "lxx": 73, "masoretic": 73, "title_ar": "ما أحسن الله لإسرائيل", "note": "" },
    { "lxx": 74, "masoretic": 74, "title_ar": "لماذا يا الله رذلتنا", "note": "" },
    { "lxx": 75, "masoretic": 75, "title_ar": "نشكرك يا الله", "note": "" },
    { "lxx": 76, "masoretic": 76, "title_ar": "معروف في يهوذا الله", "note": "" },
    { "lxx": 77, "masoretic": 77, "title_ar": "بصوتي إلى الرب صرختُ", "note": "" },
    { "lxx": 78, "masoretic": 78, "title_ar": "يا شعبي اسمع شريعتي", "note": "" },
    { "lxx": 79, "masoretic": 79, "title_ar": "يا الله دخل الوثنيون", "note": "" },
    { "lxx": 80, "masoretic": 80, "title_ar": "يا راعي إسرائيل أنصت", "note": "" },
    { "lxx": 81, "masoretic": 81, "title_ar": "ترنموا لله قوتنا", "note": "" },
    { "lxx": 82, "masoretic": 82, "title_ar": "الله يقوم في مجمع الآلهة", "note": "" },
    { "lxx": 83, "masoretic": 83, "title_ar": "يا الله لا تسكت", "note": "" },
    { "lxx": 84, "masoretic": 84, "title_ar": "ما أحب مساكنك يا رب", "note": "" },
    { "lxx": 85, "masoretic": 85, "title_ar": "أرضيت يا رب أرضك", "note": "" },
    { "lxx": 86, "masoretic": 86, "title_ar": "أمل أذنك يا رب", "note": "" },
    { "lxx": 87, "masoretic": 87, "title_ar": "أساساته في جبال القداسة", "note": "" },
    { "lxx": 88, "masoretic": 88, "title_ar": "يا رب إله خلاصي", "note": "" },
    { "lxx": 89, "masoretic": 89, "title_ar": "رحمات الرب إلى الدهر أرنم", "note": "" },
    { "lxx": 90, "masoretic": 90, "title_ar": "يا رب ملجأ كنت لنا", "note": "" },
    { "lxx": 91, "masoretic": 91, "title_ar": "الساكن في ستر العلي", "note": "" },
    { "lxx": 92, "masoretic": 92, "title_ar": "طيب أن نعترف للرب", "note": "" },
    { "lxx": 93, "masoretic": 93, "title_ar": "الرب قد ملك", "note": "" },
    { "lxx": 94, "masoretic": 94, "title_ar": "إله الانتقامات", "note": "" },
    { "lxx": 95, "masoretic": 95, "title_ar": "هلم نرنم للرب", "note": "" },
    { "lxx": 96, "masoretic": 96, "title_ar": "رنموا للرب ترنيمة جديدة", "note": "" },
    { "lxx": 97, "masoretic": 97, "title_ar": "الرب قد ملك", "note": "" },
    { "lxx": 98, "masoretic": 98, "title_ar": "رنموا للرب ترنيمة جديدة", "note": "" },
    { "lxx": 99, "masoretic": 99, "title_ar": "الرب قد ملك ترتعد الشعوب", "note": "" },
    { "lxx": 100, "masoretic": 100, "title_ar": "اهتفوا للرب يا كل الأرض", "note": "" },
    { "lxx": 101, "masoretic": 101, "title_ar": "الرحمة والحكم أرنم", "note": "" },
    { "lxx": 102, "masoretic": 102, "title_ar": "يا رب اسمع صلاتي", "note": "" },
    { "lxx": 103, "masoretic": 103, "title_ar": "باركي يا نفسي الرب", "note": "" },
    { "lxx": 104, "masoretic": 104, "title_ar": "باركي يا نفسي الرب", "note": "" },
    { "lxx": 105, "masoretic": 105, "title_ar": "احمدوا الرب ادعوا باسمه", "note": "" },
    { "lxx": 106, "masoretic": 106, "title_ar": "احمدوا الرب فإنه صالح", "note": "" },
    { "lxx": 107, "masoretic": 107, "title_ar": "احمدوا الرب فإنه صالح", "note": "" },
    { "lxx": 108, "masoretic": 108, "title_ar": "قلبى ثابت يا الله", "note": "" },
    { "lxx": 109, "masoretic": 109, "title_ar": "يا الله لا تسكت", "note": "" },
    { "lxx": 110, "masoretic": 110, "title_ar": "قال الرب لربي", "note": "" },
    { "lxx": 111, "masoretic": 111, "title_ar": "أحمد الرب من كل قلبي", "note": "" },
    { "lxx": 112, "masoretic": 112, "title_ar": "طوبى للرجل الذي يتقي الرب", "note": "" },
    { "lxx": 113, "masoretic": 113, "title_ar": "هللويا، سبحوا يا عبيد الرب", "note": "" },
    { "lxx": 114, "masoretic": 114, "title_ar": "عند خروج إسرائيل من مصر", "note": "" },
    { "lxx": 115, "masoretic": 115, "title_ar": "ليس لنا يا رب ليس لنا", "note": "" },
    { "lxx": 116, "masoretic": 116, "title_ar": "أحبت لأن الرب سمع صوتي", "note": "" },
    { "lxx": 117, "masoretic": 117, "title_ar": "سبحوا الرب يا جميع الأمم", "note": "" },
    { "lxx": 118, "masoretic": 118, "title_ar": "احمدوا الرب فإنه صالح", "note": "" },
    { "lxx": 119, "masoretic": 119, "title_ar": "طوبى للكاملين في الطريق", "note": "" },
    { "lxx": 120, "masoretic": 120, "title_ar": "إلى الرب في ضيقي صرخت", "note": "" },
    { "lxx": 121, "masoretic": 121, "title_ar": "رفعت عيني إلى الجبال", "note": "" },
    { "lxx": 122, "masoretic": 122, "title_ar": "فرحت بالقائلين لي", "note": "" },
    { "lxx": 123, "masoretic": 123, "title_ar": "إليك رفعت عيني", "note": "" },
    { "lxx": 124, "masoretic": 124, "title_ar": "لولا أن الرب كان لنا", "note": "" },
    { "lxx": 125, "masoretic": 125, "title_ar": "الذين يتكلون على الرب", "note": "" },
    { "lxx": 126, "masoretic": 126, "title_ar": "عندما رد الرب سبي صهيون", "note": "" },
    { "lxx": 127, "masoretic": 127, "title_ar": "إن لم يبن الرب البيت", "note": "" },
    { "lxx": 128, "masoretic": 128, "title_ar": "طوبى لكل من يتقي الرب", "note": "" },
    { "lxx": 129, "masoretic": 129, "title_ar": "كثيراً ما ضايقوني منذ صباي", "note": "" },
    { "lxx": 130, "masoretic": 130, "title_ar": "من الأعماق صرخت إليك يا رب", "note": "" },
    { "lxx": 131, "masoretic": 131, "title_ar": "يا رب لم يتعظم قلبي", "note": "" },
    { "lxx": 132, "masoretic": 132, "title_ar": "اذكر يا رب لداود كل تواضعه", "note": "" },
    { "lxx": 133, "masoretic": 133, "title_ar": "هو ذا ما أحسن وما أجمل", "note": "" },
    { "lxx": 134, "masoretic": 134, "title_ar": "ها باركوا الرب يا جميع عبيد الرب", "note": "" },
    { "lxx": 135, "masoretic": 135, "title_ar": "هللويا، سبحوا اسم الرب", "note": "" },
    { "lxx": 136, "masoretic": 136, "title_ar": "احمدوا الرب فإنه صالح", "note": "" },
    { "lxx": 137, "masoretic": 137, "title_ar": "على أنهار بابل هناك جلسنا", "note": "" },
    { "lxx": 138, "masoretic": 138, "title_ar": "أحمدك يا رب من كل قلبي", "note": "" },
    { "lxx": 139, "masoretic": 139, "title_ar": "يا رب أنت اختبرتني وعرفتني", "note": "" },
    { "lxx": 140, "masoretic": 140, "title_ar": "نجني يا رب من إنسان السوء", "note": "" },
    { "lxx": 141, "masoretic": 141, "title_ar": "يا رب إليك صرخت", "note": "" },
    { "lxx": 142, "masoretic": 142, "title_ar": "بصوتي إلى الرب صرخت", "note": "" },
    { "lxx": 143, "masoretic": 143, "title_ar": "يا رب اسمع صلاتي", "note": "" },
    { "lxx": 144, "masoretic": 144, "title_ar": "مبارك الرب صخرتي", "note": "" },
    { "lxx": 145, "masoretic": 145, "title_ar": "أعظمك يا إلهي الملك", "note": "" },
    { "lxx": 146, "masoretic": 146, "title_ar": "هللويا، سبحى يا نفسى الرب", "note": "" },
    { "lxx": 147, "masoretic": 147, "title_ar": "هللويا، لأنه صالح التسبيح", "note": "" },
    { "lxx": 148, "masoretic": 148, "title_ar": "هللويا، سبحوا الله في السماوات", "note": "" },
    { "lxx": 149, "masoretic": 149, "title_ar": "هللويا، رنموا للرب ترنيمة جديدة", "note": "" },
    { "lxx": 150, "masoretic": 150, "title_ar": "هللويا، سبحوا الله في قديسيه", "note": "" },
    { "lxx": 151, "masoretic": 151, "title_ar": "صغير كنت في أخوتي", "note": "مزمور 151 السبعيني - غير موجود في النص الماسوريتي، موجود في الترجمة السبعينية والسريانية" }
]

data = {"table": "psalms_mapping", "rows": rows}

with open('content_src/reference/psalms_mapping.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Done")